### ISSUE TITLE
Erro ao gerar .txt para planilha ODS

### ISSUE THREAD

**Issue by HelderSamuelBR** [OpenGeoOne/GeoINCRA#2]
Criei os campos dos arquivos vetoriais conforme orientação da WIKI, mas ao tentar gerar o .txt aparece sempre o seguinte erro:

Traceback (most recent call last):
File "C:/Users/helde/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoINCRA\algorithms\createTemplate.py", line 143, in processAlgorithm
if not feature['Código do Vértice']:
KeyError

Do que se trata o erro?

**Comment by OpenGeoOne** [comment]
Olá Helder,

Verifica se você está usando o modelo do banco correto ou deixou de preencher o campo código do vértice.

No nosso curso de GeoINCRA no QGIS, a gente disponibiliza um projeto do QGIS pronto com o modelo GeoRural e aulas passo a passo que podem ajudar nos seus trabalhos.
Segue o link, caso tenha interesse: https://pay.hotmart.com/X69158193B?checkoutMode=10

**Comment by LEOXINGU** [comment]
A nova versão do plugin vai resolver esse problema e indicar possíveis erros na estrutura do banco de dados ou no preenchimento dos atributos quando rodar a ferramenta.
